### ISSUE TITLE
how to use microTVM

### ISSUE THREAD

**Issue by msnagar** [PhilippvK/microtvm-gvsoc-template#2]
Dear Philip,
I want to use the microTVM with gvsoc. Is there any sample examples that we can run on GVSoC with microTVM.

**Comment by PhilippvK** [comment]
Hello @msnagar! This is still a work in progress. I will try to add some Documentation on how to set this up in the following days. Thank you in advance for your patience!

**Comment by PhilippvK** [comment]
I just added an extensive README for the repository: https://github.com/PhilippvK/microtvm-gvsoc-template/blob/main/README.md

I hope this answers your question!
